### ISSUE TITLE
We need your project to be in the root directory

### ISSUE THREAD

**Issue by aarongustafson** [kregioncz/kameny#1]
Also, the server will be IIS, so you will need to use a web.config file instead of .htaccess. There’s a translation tool though: http://cbsa.com.br/tools/online-convert-htaccess-to-web-config.aspx

**Comment by kregioncz** [comment]
I have moved to root dir and made a Web.Config file... but I don't know if it will work on IIS with this configuration... I'm only trying to turn static and dynamic compression on.

**Comment by aarongustafson** [comment]
I will try to deploy it again.
